update hz_cust_acct_sites_all a 
set attribute4 = null,
attribute5 = null;


update HZ_CUST_ACCT_SITES_ALL set attribute4 ='C3436-26299-C' , attribute5 ='C3436-26299-C' where org_id = SAP_TOOLS_CC.soc_to_org_id('410') and cust_account_id = ( select cust_account_id from hz_cust_accounts where account_number = '3436') and party_site_id = ( select party_site_id from hz_party_sites where party_site_number  ='26299-C' ) ;
update HZ_CUST_ACCT_SITES_ALL set attribute4 ='C3436-26299-C', attribute5 ='C3436-4637-C' where org_id = SAP_TOOLS_CC.soc_to_org_id('437') and cust_account_id = ( select cust_account_id from hz_cust_accounts where account_number = '3436') and party_site_id = ( select party_site_id from hz_party_sites where party_site_number  ='4637-C');
update HZ_CUST_ACCT_SITES_ALL set attribute4 ='C3051-26385-C', attribute5 ='C3051-26385-C' where org_id = SAP_TOOLS_CC.soc_to_org_id('437') and cust_account_id = ( select cust_account_id from hz_cust_accounts where account_number = '3051') and party_site_id = ( select party_site_id from hz_party_sites where party_site_number  ='26385-C');
update HZ_CUST_ACCT_SITES_ALL set attribute4 ='C2885-4056-C', attribute5 ='C2885-4056-C' where org_id = SAP_TOOLS_CC.soc_to_org_id('437') and cust_account_id = ( select cust_account_id from hz_cust_accounts where account_number = '2885') and party_site_id = ( select party_site_id from hz_party_sites where party_site_number  ='4056-C');
update HZ_CUST_ACCT_SITES_ALL set attribute4 ='C10439-57611', attribute5 ='C10439-57611' where org_id = SAP_TOOLS_CC.soc_to_org_id('410') and cust_account_id = ( select cust_account_id from hz_cust_accounts where account_number = '10439') and party_site_id = ( select party_site_id from hz_party_sites where party_site_number  ='57611');
update HZ_CUST_ACCT_SITES_ALL set attribute4 ='C10439-64991', attribute5 ='C10439-64991' where org_id = SAP_TOOLS_CC.soc_to_org_id('437') and cust_account_id = ( select cust_account_id from hz_cust_accounts where account_number = '10439') and party_site_id = ( select party_site_id from hz_party_sites where party_site_number  ='64991');
update HZ_CUST_ACCT_SITES_ALL set attribute4 ='C26255-34959-C', attribute5 ='C26255-34959-C' where org_id = SAP_TOOLS_CC.soc_to_org_id('100') and cust_account_id = ( select cust_account_id from hz_cust_accounts where account_number = '26255') and party_site_id = ( select party_site_id from hz_party_sites where party_site_number  ='34959-C');
update HZ_CUST_ACCT_SITES_ALL set attribute4 ='C26255-34959-C', attribute5 ='C26255-34959-C' where org_id = SAP_TOOLS_CC.soc_to_org_id('504') and cust_account_id = ( select cust_account_id from hz_cust_accounts where account_number = '26255') and party_site_id = ( select party_site_id from hz_party_sites where party_site_number  ='34959-C');
update HZ_CUST_ACCT_SITES_ALL set attribute4 ='C3436-26299-C', attribute5 ='C3436-26299-C' where org_id = SAP_TOOLS_CC.soc_to_org_id('100') and cust_account_id = ( select cust_account_id from hz_cust_accounts where account_number = '3436') and party_site_id = ( select party_site_id from hz_party_sites where party_site_number  ='26299-C');
update HZ_CUST_ACCT_SITES_ALL set attribute4 ='C3436-26299-C', attribute5 ='C3436-26299-C' where org_id = SAP_TOOLS_CC.soc_to_org_id('410') and cust_account_id = ( select cust_account_id from hz_cust_accounts where account_number = '3436') and party_site_id = ( select party_site_id from hz_party_sites where party_site_number  ='26299-C');
update HZ_CUST_ACCT_SITES_ALL set attribute4 ='C3436-26299-C', attribute5 ='C3436-4637-C' where org_id = SAP_TOOLS_CC.soc_to_org_id('437') and cust_account_id = ( select cust_account_id from hz_cust_accounts where account_number = '3436') and party_site_id = ( select party_site_id from hz_party_sites where party_site_number  ='4637-C');
update HZ_CUST_ACCT_SITES_ALL set attribute4 ='C3725-45179', attribute5 ='C3725-32563-C' where org_id = SAP_TOOLS_CC.soc_to_org_id('415') and cust_account_id = ( select cust_account_id from hz_cust_accounts where account_number = '3725') and party_site_id = ( select party_site_id from hz_party_sites where party_site_number  ='28272-C');
update HZ_CUST_ACCT_SITES_ALL set attribute4 ='C3725-45179', attribute5 ='C3725-28497-C' where org_id = SAP_TOOLS_CC.soc_to_org_id('437') and cust_account_id = ( select cust_account_id from hz_cust_accounts where account_number = '3725') and party_site_id = ( select party_site_id from hz_party_sites where party_site_number  ='28497-C');
update HZ_CUST_ACCT_SITES_ALL set attribute4 ='C3725-45179', attribute5 ='C3725-32563-C' where org_id = SAP_TOOLS_CC.soc_to_org_id('415') and cust_account_id = ( select cust_account_id from hz_cust_accounts where account_number = '3725') and party_site_id = ( select party_site_id from hz_party_sites where party_site_number  ='32563-C');
update HZ_CUST_ACCT_SITES_ALL set attribute4 ='C3725-45179', attribute5 ='C3725-45179' where org_id = SAP_TOOLS_CC.soc_to_org_id('100') and cust_account_id = ( select cust_account_id from hz_cust_accounts where account_number = '3725') and party_site_id = ( select party_site_id from hz_party_sites where party_site_number  ='32740-C');
update HZ_CUST_ACCT_SITES_ALL set attribute4 ='C3725-45179', attribute5 ='C3725-45179' where org_id = SAP_TOOLS_CC.soc_to_org_id('100') and cust_account_id = ( select cust_account_id from hz_cust_accounts where account_number = '3725') and party_site_id = ( select party_site_id from hz_party_sites where party_site_number  ='45179');
update HZ_CUST_ACCT_SITES_ALL set attribute4 ='C3725-45179', attribute5 ='C3725-45179' where org_id = SAP_TOOLS_CC.soc_to_org_id('100') and cust_account_id = ( select cust_account_id from hz_cust_accounts where account_number = '3725') and party_site_id = ( select party_site_id from hz_party_sites where party_site_number  ='4958-C');
update HZ_CUST_ACCT_SITES_ALL set attribute4 ='C3725-45179', attribute5 ='C3725-45179' where org_id = SAP_TOOLS_CC.soc_to_org_id('100') and cust_account_id = ( select cust_account_id from hz_cust_accounts where account_number = '3725') and party_site_id = ( select party_site_id from hz_party_sites where party_site_number  ='52838');
update HZ_CUST_ACCT_SITES_ALL set attribute4 ='C3725-45179', attribute5 ='C3725-57890' where org_id = SAP_TOOLS_CC.soc_to_org_id('410') and cust_account_id = ( select cust_account_id from hz_cust_accounts where account_number = '3725') and party_site_id = ( select party_site_id from hz_party_sites where party_site_number  ='57890');
update HZ_CUST_ACCT_SITES_ALL set attribute4 ='C3767-23520-C', attribute5 ='C3767-23520-C' where org_id = SAP_TOOLS_CC.soc_to_org_id('437') and cust_account_id = ( select cust_account_id from hz_cust_accounts where account_number = '3767') and party_site_id = ( select party_site_id from hz_party_sites where party_site_number  ='23520-C');
update HZ_CUST_ACCT_SITES_ALL set attribute4 ='C51657-46971', attribute5 ='C51657-46971' where org_id = SAP_TOOLS_CC.soc_to_org_id('100') and cust_account_id = ( select cust_account_id from hz_cust_accounts where account_number = '51657') and party_site_id = ( select party_site_id from hz_party_sites where party_site_number  ='46971');
update HZ_CUST_ACCT_SITES_ALL set attribute4 ='C51657-46971', attribute5 ='C51657-46971' where org_id = SAP_TOOLS_CC.soc_to_org_id('437') and cust_account_id = ( select cust_account_id from hz_cust_accounts where account_number = '51657') and party_site_id = ( select party_site_id from hz_party_sites where party_site_number  ='46971');
update HZ_CUST_ACCT_SITES_ALL set attribute4 ='C51657-55552', attribute5 ='C51657-55552' where org_id = SAP_TOOLS_CC.soc_to_org_id('410') and cust_account_id = ( select cust_account_id from hz_cust_accounts where account_number = '51657') and party_site_id = ( select party_site_id from hz_party_sites where party_site_number  ='55552');
update HZ_CUST_ACCT_SITES_ALL set attribute4 ='C51657-55552', attribute5 ='C51657-55552' where org_id = SAP_TOOLS_CC.soc_to_org_id('437') and cust_account_id = ( select cust_account_id from hz_cust_accounts where account_number = '51657') and party_site_id = ( select party_site_id from hz_party_sites where party_site_number  ='55552');
update HZ_CUST_ACCT_SITES_ALL set attribute4 ='C4324-33915-C', attribute5 ='C4324-22261-C' where org_id = SAP_TOOLS_CC.soc_to_org_id('437') and cust_account_id = ( select cust_account_id from hz_cust_accounts where account_number = '4324') and party_site_id = ( select party_site_id from hz_party_sites where party_site_number  ='22261-C');
update HZ_CUST_ACCT_SITES_ALL set attribute4 ='C4324-33915-C', attribute5 ='C4324-22262-C' where org_id = SAP_TOOLS_CC.soc_to_org_id('504') and cust_account_id = ( select cust_account_id from hz_cust_accounts where account_number = '4324') and party_site_id = ( select party_site_id from hz_party_sites where party_site_number  ='22262-C');
update HZ_CUST_ACCT_SITES_ALL set attribute4 ='C4324-33915-C', attribute5 ='C4324-28283-C' where org_id = SAP_TOOLS_CC.soc_to_org_id('415') and cust_account_id = ( select cust_account_id from hz_cust_accounts where account_number = '4324') and party_site_id = ( select party_site_id from hz_party_sites where party_site_number  ='28283-C');
update HZ_CUST_ACCT_SITES_ALL set attribute4 ='C4324-33915-C', attribute5 ='C4324-33915-C' where org_id = SAP_TOOLS_CC.soc_to_org_id('410') and cust_account_id = ( select cust_account_id from hz_cust_accounts where account_number = '4324') and party_site_id = ( select party_site_id from hz_party_sites where party_site_number  ='33915-C');
update HZ_CUST_ACCT_SITES_ALL set attribute4 ='C55731-67925', attribute5 ='C55731-58483' where org_id = SAP_TOOLS_CC.soc_to_org_id('504') and cust_account_id = ( select cust_account_id from hz_cust_accounts where account_number = '55731') and party_site_id = ( select party_site_id from hz_party_sites where party_site_number  ='58483');
update HZ_CUST_ACCT_SITES_ALL set attribute4 ='C55731-67925', attribute5 ='C55731-67925' where org_id = SAP_TOOLS_CC.soc_to_org_id('100') and cust_account_id = ( select cust_account_id from hz_cust_accounts where account_number = '55731') and party_site_id = ( select party_site_id from hz_party_sites where party_site_number  ='67925');
update HZ_CUST_ACCT_SITES_ALL set attribute4 ='C55731-67925', attribute5 ='C57002-62148' where org_id = SAP_TOOLS_CC.soc_to_org_id('985') and cust_account_id = ( select cust_account_id from hz_cust_accounts where account_number = '57002') and party_site_id = ( select party_site_id from hz_party_sites where party_site_number  ='62148');

update hz_cust_acct_sites_all a 
set attribute4 = ( select 'C' || hca.account_number || '-' || to_char(hps.party_site_number)
                  from hz_cust_accounts hca , hz_cust_acct_sites_all hcasa , hz_party_sites hps
                  where hca.CUST_ACCOUNT_ID = hcasa.CUST_ACCOUNT_ID
                  and hps.party_site_id = hcasa.party_site_id
                  and hcasa.cust_acct_site_id = a.cust_acct_site_id),
    attribute5 = ( select 'C' || hca.account_number || '-' || to_char(hps.party_site_number)
                  from hz_cust_accounts hca , hz_cust_acct_sites_all hcasa , hz_party_sites hps
                  where hca.CUST_ACCOUNT_ID = hcasa.CUST_ACCOUNT_ID
                  and hps.party_site_id = hcasa.party_site_id
                  and hcasa.cust_acct_site_id = a.cust_acct_site_id)
where attribute4 is null;

